#!/bin/sh

# Gearman server and library
# Copyright (C) 2008 Brian Aker, Eric Day
# All rights reserved.
#
# Use and distribution licensed under the BSD license.  See
# the COPYING file in this directory for full text.

SKYDATADIR="/var/lib/skysql"
SKYBASEDIR=$(dirname $0)/../..
cd $SKYBASEDIR
export SKYBASEDIR=$(pwd)
export SKYDATADIR=$SKYDATADIR
export PATH=$PATH:$SKYBASEDIR/sandbox/bin/:$SKYBASEDIR/gearmand/bin/:$SKYBASEDIR/gearmand/sbin/:$SKYBASEDIR/mariadb-client/bin/
export PERL5LIB=$SKYBASEDIR/sandbox/lib/site_perl/5.16.0:$SKYBASEDIR/perl/lib/site_perl/5.16.0/darwin-2level
export SANDBOX_AS_ROOT=1
export PYTHONUSERBASE=$SKYBASEDIR/MySQL-python
export PYTHONPATH=$SKYBASEDIR/MySQL-python/lib64/python2.6
export LD_LIBRARY_PATH=$SKYBASEDIR/mysql-client/lib/

cd $SKYBASEDIR/ncc

if [ ! -d $SKYDATADIR ];
then
   mkdir $SKYDATADIR  
fi
if [ ! -d $SKYDATADIR/log ];
then
   mkdir $SKYDATADIR/log  
fi
if [ ! -d $SKYDATADIR/dbt2 ];
then
   mkdir $SKYDATADIR/dbt2  
fi
if [ ! -d $SKYDATADIR/dbt3 ];
then
   mkdir $SKYDATADIR/dbt3  
fi
if [ ! -d $SKYDATADIR/sandboxes ];
then
  mkdir $SKYDATADIR/sandboxes  
fi

echo 1 > /proc/sys/net/ipv4/tcp_tw_recycle
echo 1024 > /proc/sys/net/core/somaxconn
echo 4096 > /proc/sys/net/ipv4/tcp_max_syn_backlog

GEARMAND=$SKYBASEDIR/gearmand/sbin/gearmand
PIDFILE=$SKYBASEDIR/ncc/tmp/gearmand.pid
LOG=$SKYDATADIR/log
WORKER=$SKYBASEDIR/ncc/bin/worker_node_cmd.pl 
WORKERCLUSTER=$SKYBASEDIR/ncc/bin/worker_cluster_cmd.pl 
WORKERCONFIG=$SKYBASEDIR/ncc/bin/worker_write_config.pl
WORKERHEARBEAT=$SKYBASEDIR/ncc/bin/worker_heartbeat.pl
start()
{

  nohup $GEARMAND -P $PIDFILE  -d --log-file=$SKYDATADIR/log/gearmand.log &
  procid=$!
  echo $procid >> $PIDFILE 
  nohup $SKYBASEDIR/perl/bin/perl $WORKER  < /dev/null > $LOG/worker_node.log 2>&1 & 
  procid=$!
  echo $procid >> $SKYBASEDIR/ncc/tmp/wrk$procid.pid
  nohup $SKYBASEDIR/perl/bin/perl $WORKERCLUSTER < /dev/null > $LOG/worker_cluster.log 2>&1 & 
  procid=$!
  echo $procid >> $SKYBASEDIR/ncc/tmp/wrk$procid.pid
  nohup $SKYBASEDIR/perl/bin/perl $WORKERCONFIG < /dev/null > $LOG/worker_config.log 2>&1 & 
  procid=$!
  echo $procid >> $SKYBASEDIR/ncc/tmp/wrk$procid.pid  
  nohup $SKYBASEDIR/perl/bin/perl $WORKERHEARBEAT < /dev/null > $LOG/worker_hearbeat.log 2>&1 & 
  procid=$!
  echo $procid >> $SKYBASEDIR/ncc/tmp/wrk$procid.pid  

}

stop()
{
  kill `cat $PIDFILE`
  rm -f $PIDFILE
  _dfiles="$SKYBASEDIR/ncc/tmp/wrk*.pid"
 
for f in $_dfiles
do

  kill `cat $f`
  rm -f $f
done  

}

case "$1" in

  start)
    start
  ;;

  stop)
    stop
  ;;

  restart)
    stop
    start
  ;;

  *)
    echo "Usage: $0 {start|stop|restart}"
  ;;

esac

